SELECT ?region ?regionLabel (COUNT(DISTINCT ?item) AS ?cnt)
WHERE {
  ?item wdt:P31 wd:Q483110 ;
        wdt:P17 wd:Q38 ;
        wdt:P131 ?region .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
GROUP BY ?region ?regionLabel
HAVING (COUNT(DISTINCT ?item) >= 3)
ORDER BY DESC(?cnt) ?region
LIMIT 10
